from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai import Credentials
from langchain_ibm import WatsonxLLM
from langchain_community.vectorstores import Chroma

import os
from langchain.prompts import ChatPromptTemplate
from langchain.schema.output_parser import StrOutputParser
from langchain.schema.runnable import RunnablePassthrough
from huggingface_hub import HfFolder

from langchain.retrievers import ParentDocumentRetriever
from langchain.storage import InMemoryStore
from langchain.text_splitter import RecursiveCharacterTextSplitter

import gradio as gr

from doc_load_embbed import document_loader
from doc_load_embbed import watsonx_embedding

from langchain.memory import ChatMessageHistory
from langchain.prompts import MessagesPlaceholder



# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

## LLM
def get_llm():
    model_id = 'ibm/granite3.3-vision:2b'
    parameters = {
        GenParams.MAX_NEW_TOKENS: 256,  
        GenParams.TEMPERATURE: 0.5,
    }
    project_id = "skills-network"
    watsonx_llm = WatsonxLLM(
        model_id=model_id,
        url="https://us-south.ml.cloud.ibm.com",
        project_id=project_id,
        params=parameters,
    )
    return watsonx_llm

## Retriever

def retriever(file): ## We can consider work with ParentDocumentRetriever.
    parent_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=100,
    )

    child_splitter = RecursiveCharacterTextSplitter(
        chunk_size=200,
        chunk_overlap=20,
    )

    embedding = watsonx_embedding()

    vectorstore = Chroma(
    collection_name="split_parents", embedding_function=embedding
    )
# The storage layer for the parent documents
    store = InMemoryStore()

    retriever = ParentDocumentRetriever(
    vectorstore=vectorstore,
    docstore=store,
    child_splitter=child_splitter,
    parent_splitter=parent_splitter,
    )

    splits = document_loader(file)
    retriever.add_documents(splits)
    return retriever

## QA Chain
chat_history = ChatMessageHistory()

def retriever_qa(file, query):
    llm = get_llm()

    #if file is None:
    #    return llm.invoke(query).content
    
    retriever_obj = retriever(file)

    prompt_wo = ChatPromptTemplate.from_messages([
    ("system", "請根據以下內容回答問題。"),
    MessagesPlaceholder("history"),
    ("human", "{question}")
    ])
    
    prompt = ChatPromptTemplate.from_messages([
    ("system", "請根據以下內容回答問題。\n\n{context}"),
    MessagesPlaceholder("history"),
    ("human", "{question}")
    ])

    def format_docs(docs):
        return "\n\n".join(doc.page_content for doc in docs)
    if file is None:
        chain = (
            {
                "question": RunnablePassthrough(),
                "history": lambda _: chat_history.messages
            }
            | prompt_wo
            | llm
            | StrOutputParser()
        )
    else:
        chain = (
            {
                "context": retriever_obj | format_docs,
                "question": RunnablePassthrough(),
                "history": lambda _: chat_history.messages
            }
            | prompt
            | llm
            | StrOutputParser()
        )

    response = chain.invoke(query)
    chat_history.add_user_message(query)
    chat_history.add_ai_message(response)
    return response#['result']

# Create Gradio interface
rag_application = gr.Interface(
    fn=retriever_qa,
    allow_flagging="never",
    inputs=[
        gr.File(label="Upload PDF File", file_count="single", file_types=['.pdf'], type="filepath"),  # Drag and drop file upload
        gr.Textbox(label="Input Query", lines=2, placeholder="Type your question here...")
    ],
    outputs=gr.Textbox(label="Output"),
    title="Watsonx.ai Chatbot",
    description="Upload a PDF document and ask any question. The chatbot will try to answer using the provided document."
)

# Launch the app
rag_application.launch(server_name="127.0.0.1", server_port= 7860)
