from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai import Credentials
from langchain_ibm import WatsonxLLM
from langchain_community.vectorstores import Chroma

import os
from langchain.chains import RetrievalQA
from huggingface_hub import HfFolder

from langchain.retrievers import ParentDocumentRetriever
from langchain.storage import InMemoryStore
from langchain.text_splitter import RecursiveCharacterTextSplitter

import gradio as gr

from doc_load_embbed import document_loader
from doc_load_embbed import watsonx_embedding


# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

## LLM
def get_llm():
    model_id = 'ibm/granite-3.x-vision-instruct'
    parameters = {
        GenParams.MAX_NEW_TOKENS: 256,  
        GenParams.TEMPERATURE: 0.5,
    }
    project_id = "skills-network"
    watsonx_llm = WatsonxLLM(
        model_id=model_id,
        url="https://us-south.ml.cloud.ibm.com",
        project_id=project_id,
        params=parameters,
    )
    return watsonx_llm

## Retriever
vectorstore_global = None

#def build_vectorstore(file):

    #return vectorstore, parent_splitter, child_splitter


def retriever(file): ## We can consider work with ParentDocumentRetriever.

# The storage layer for the parent documents
    global retriever_global
    parent_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=100,
    )

    child_splitter = RecursiveCharacterTextSplitter(
        chunk_size=200,
        chunk_overlap=20,
    )

    splits = document_loader(file)
    
    embedding = watsonx_embedding()

    vectorstore = Chroma.from_documents(
        documents=splits, collection_name="split_parents", embedding_function=embedding
    )
    
    store = InMemoryStore()

    retriever_global = ParentDocumentRetriever(
    vectorstore=vectorstore,
    docstore=store,
    child_splitter=child_splitter,
    parent_splitter=parent_splitter,
    )
 
    retriever_global.add_documents(splits)
    return retriever_global

## QA Chain
def retriever_qa(retriever, query):
    global retriever_global
    if retriever_global is None:
        return "請先上傳 PDF 並建立 retriever"
    llm = get_llm()
    qa = RetrievalQA.from_chain_type(llm=llm, 
                                    chain_type="stuff", 
                                    retriever=retriever_global, 
                                    return_source_documents=False)
    response = qa.invoke(query)
    return response['result']

# Create Gradio interface
rag_application = gr.Interface(
    fn=retriever_qa,
    allow_flagging="never",
    inputs=[
        gr.File(label="Upload PDF File", file_count="single", file_types=['.pdf'], type="filepath"),  # Drag and drop file upload
        gr.Textbox(label="Input Query", lines=2, placeholder="Type your question here...")
    ],
    outputs=gr.Textbox(label="Output"),
    title="Watsonx.ai Chatbot",
    description="Upload a PDF document and ask any question. The chatbot will try to answer using the provided document."
)

# Launch the app
rag_application.launch(server_name="127.0.0.1", server_port= 7860)
